# Generated by Django 5.2.11 on 2026-02-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (takes priority over uploaded image)', verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_url',
            field=models.URLField(blank=True, help_text='External photo URL (takes priority over uploaded photo)', verbose_name='Photo URL'),
        ),
    ]
