# Generated by Django 5.2.11 on 2026-02-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_image_url_teammember_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('demo', 'Демонстрационный'), ('completed', 'Выполненный'), ('partner', 'Компания-партнёр')], default='demo', max_length=20, verbose_name='Category'),
        ),
    ]
