# Generated by Django 5.2.11 on 2026-02-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
